# Generated by Django 2.1.3 on 2018-12-10 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('autor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=30)),
                ('idioma', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=20)),
                ('titular', models.CharField(max_length=80)),
                ('resumen', models.CharField(max_length=300)),
                ('autores', models.ManyToManyField(to='diario_app.Autor')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario_app.Diario')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('tipo_noticia', models.CharField(max_length=80, primary_key=True, serialize=False, unique=True, verbose_name='Tipos noticias')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre_usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='noticia',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario_app.Tipo'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='usuarios_interesados',
            field=models.ManyToManyField(to='diario_app.Usuario'),
        ),
    ]
